[package]
name = "terminal-madness"
version = "0.1.0"
authors = ["Dennis Pettersson"]
edition = "2018"

[dependencies]
termion = "1.5.4"
lazy_static = "1.4.0"
float-cmp = "0.6.0"
rand = "0.7.2"

[profile.release]
lto = true
panic = "abort"
